name: Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-front:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './front/package-lock.json'      
        
    - run: npm ci
      working-directory: ./front/

    - name: run test and generate code coverage
      run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
      working-directory: ./front/

    - name: Cache front coverage
      uses: actions/cache@v3
      with:
        path: front/coverage
        key: front-coverage-${{ github.sha }}
        restore-keys: |
          front-coverage-

    - name: Generate front report 
      uses: actions/upload-artifact@v4.3.3
      with:
        name: Front-report
        path: front/coverage

    - name: Badge with front coverage
      uses:  demyanets/angular-coverage-badges-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coverage-summary-path: front/coverage/bobapp/coverage-summary.json
        protected-branches: '["master"]'
        badges-directory: badges/bobapp

    - name: Commit and push badges
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add badges/bobapp
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update front-end coverage badges"
          git push origin main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  test-back:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and test with Maven
        run: |
          mvn -B package --file pom.xml
          mvn -B test --file pom.xml   
        working-directory: ./back/

      - name: Cache back coverage
        uses: actions/cache@v3
        with:
          path: back/target/site/jacoco
          key: back-coverage-${{ github.sha }}
          restore-keys: |
            back-coverage-

      - name: Generate back report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Back-report
          path: back/target/site/jacoco/

      - name: Badge with back coverage
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: back/target/site/jacoco/jacoco.csv
          badges-directory: badges/bobapp
          generate-coverage-badge: true
          coverage-badge-filename: backendBadge.svg

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push badges
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add badges/bobapp
          if git diff --staged --quiet; then
          echo "No changes to commit"
          else
            git commit -m "Update back-end coverage badges"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
